/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a DBusShareAdaptorWrapper.hpp:DBusShareAdaptorWrapper.cpp -c DBusShareAdaptorWrapper C:\Users\cheiv\Documents\Projects\SailfishOS\fromBigTower\depecher\depecher\dbus\org.blacksailer.depecher.share.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DBusShareAdaptorWrapper.hpp"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusShareAdaptorWrapper
 */

DBusShareAdaptorWrapper::DBusShareAdaptorWrapper(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusShareAdaptorWrapper::~DBusShareAdaptorWrapper()
{
    // destructor
}

QDBusVariant DBusShareAdaptorWrapper::getChatList(qint64 last_chat_id, qint64 order, const QDBusMessage &message)
{
    // handle method call org.blacksailer.depecher.share.getChatList
    QVariant chatVariant;
    message.setDelayedReply(true);
    qDebug() << "Wrppaer dbus";
    QMetaObject::invokeMethod(parent(), "getChatList",
                              Q_RETURN_ARG(QVariant, chatVariant),
                              Q_ARG(qint64, last_chat_id),
                              Q_ARG(qint64, order),
                              Q_ARG(QDBusMessage, message));
    return QDBusVariant(chatVariant);
}

void DBusShareAdaptorWrapper::sendMedia(const QList<qlonglong> &chat_ids, const QString &filepath, const QString &mimeType)
{
    // handle method call org.blacksailer.depecher.share.sendMedia
    QMetaObject::invokeMethod(parent(), "sendMedia",
                              Q_ARG(QList<qlonglong>, chat_ids),
                              Q_ARG(QString, filepath),
                              Q_ARG(QString, mimeType)
                             );
}

void DBusShareAdaptorWrapper::sendVCard(const QList<qlonglong> &chat_ids, const QString &data)
{
    // handle method call org.blacksailer.depecher.share.sendVCard
    QMetaObject::invokeMethod(parent(), "sendVCard",
                              Q_ARG(QList<qlonglong>, chat_ids),
                              Q_ARG(QString, data));
}

